name = "Lox"
grammar = "lox"
path_suffixes = ["lox"]
line_comments = ["// "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
